ESIOS_API_KEY="496b263791ef0dcaf80b803b47b332a13b01f2c2352e018b624c7a36a0eaffc0"
PASSWORD_GMAIL="rwrd kvfr wrfv qfct"
ID_DRIVE_TELEMINDEX = '1QVWiORLQGHGFkjUeegxpIdwR6yj2gJr9uj4XZjHhrjU'
ID_DRIVE_USERS = '1kvtwjmvUhNjHlnA6nS9BI0ExwC8czTina-b4zBLcWVM'
ID_DRIVE_APUESTAS = '1y3Zd6phwut0yDKX8rB_t7xvJ6J3pLV95P6VQxvl3fu8'
ID_DRIVE_MEFF = '1VELR6AaajSeHYbv6QSgDXBWkCNv0z-uzVa5jAk57i4I'

